---
- name: Install webserver packages
  hosts: wb
  vars_files:
    - vars/default.yml

  tasks:
  - name: Install software-properties-common
    apt: name=software-properties-common

  - name: Install 7.4 repo
    apt_repository:
      repo="ppa:ondrej/php"

  - name: Update apt cache
    apt: update_cache=yes

  - name: Install PHP 7.4
    apt:
      name: php7.4
      state: present

  - name: Install default PHP packages
    apt:
      pkg:
        - php7.4-mysql
        - php7.4-curl
        - php7.4-json
        - php7.4-cgi
        - php7.4-xsl
        - php7.4-cgi
        - php7.4-gd
        - php7.4-mbstring
        - php7.4-zip
        - php7.4-xmlrpc
        - php7.4-soap
        - php7.4-intl
        - libapache2-mod-php
      state: present
      update_cache: yes

  - name: Install prerequisites
    apt: name={{ item }} update_cache=yes state=latest force_apt_get=yes
    loop: [ 'aptitude' ]

  - name: Install Apache
    apt: name=apache2 update_cache=yes state=latest

  - name: Create document root
    file:
      path: "/var/www/{{ http_host }}"
      state: directory
      owner: "{{ app_user }}"
      mode: '0755'

  - name: Copy index test page
    template:
      src: "files/index.html.j2"
      dest: "/var/www/{{ http_host }}/index.html"

  - name: Copy phpinfo
    template:
      src: "files/info.php.j2"
      dest: "/var/www/{{ http_host }}/info.php"

  - name: Set up Apache virtualhost
    template:
      src: "files/apache.conf.j2"
      dest: "/etc/apache2/sites-available/{{ http_conf }}"

  - name: Enable new site
    shell: /usr/sbin/a2ensite {{ http_conf }}
    notify: Reload Apache

  - name: Disable default Apache site
    shell: /usr/sbin/a2dissite 000-default.conf
    when: disable_default
    notify: Reload Apache

  - name: "UFW - Allow HTTP on port {{ http_port }}"
    ufw:
      rule: allow
      port: "{{ http_port }}"
      proto: tcp

  handlers:
  - name: Reload Apache
    service:
      name: apache2
      state: reloaded

  - name: Restart Apache
    service:
      name: apache2
      state: restarted
