---
- hosts: all

  tasks:
  - name: Install shared packages
    apt:
      name:
      - python3
      - htop
      - atop
      - vim
      - netcat
      - pwgen
      - net-tools
      state: present
      update_cache: yes
